#数据库连接池
spring:
  datasource:
    username: root
    password: illya0415
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://bootzhong.top:3306/bili?useUnicode=true&charaterEncoding=UTF-8&serverTimezone=UTC
#    url: jdbc:mysql://localhost:3306/bili?useUnicode=true&charaterEncoding=UTF-8&serverTimezone=UTC

#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#    name: mysql_ds
#    url: jdbc:mysql://gz-cdb-f7xa45k3.sql.tencentcdb.com:60216/iot_base_admin?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8
#    username: root
#    password: sawXG841rx

#redis
  redis:
    host: 127.0.0.1
    port: 6379
    password: illya0415
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    timeout: 2000
    database: 1

#redis数据源2
  redis2:
    host: 127.0.0.1
    port: 6379
    password: illya0415
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
    timeout: 2000
    database: 2

#服务器配置
server:
  port: 8082
  servlet:
    context-path: /bili

#mybatis
mybatis:
  mapper-locations: classpath:mapper/*.xml
